# Generated by Django 4.0.5 on 2022-07-10 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='polarity_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='subjectivity_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='polarity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='subjectivity',
            field=models.FloatField(null=True),
        ),
    ]
